apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://cloudlite-prometheus-server
        isDefault: true
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://cloudlite-loki:3100
