---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: cloudlite
spec:
  encryptedData:
    admin-password: AgBWkTwUBYxPAcwJl8+8D+UZbGGRdM5r8+5iNkOuqv64johs9oFfSSIXpuDGKJkZBIx4Fq1PNp8QJqkSvBsm8gWTI0micw7aTaRPAG3NlAUopm4lSXw94wZ4BR2YJ/u56tDmFxKMC+XdnAp8PgCNC5Dk6Z2axtFkeCDRM0AWEunpYS11LLboyQW1sawwAerq7uCLvtFvFgb/pMs+61GUNzrbmUiU2yvegZAVZmdwr+RbBHzFv1cePDxYGlHxwgHRjM7e5LnEbSsfhD8JqExQjN3PBw0r45BiIR3dWZU/NkiQ3OKXZpS7RvGWuIfQf0wQhoy4yQhauMcux8F4iSOHFlYuQICvVx25FFKQpgCGObfwL0BFG4xGfGFiCAUD+rNFNqf0jdwdOCkGi6h098cC4nycTBi/FzDcCgiHMq9ex4tkq4k+Xqz3qtPgVpI6mb3C4bdvSCiBEJ/lgvwG9KFemIU84QJ8CJi7DLoPDZrgBrarERCYSThm9NGTU9r7DVZ3zoIuPNbxhrUIX1Q8lIl93vEmOA8DwPVt+XW2fT4tHyDgLBLUHicfPIbk7G7+V+EesJCxVOxi+x/iBMo2aiicLDwfawzO8TiYttzl62Nm+/pFNaLHqTI+pKHO03AzjiB0tn+3I7fPzgvRKhgjPWNKt6ZXgaayeaR5dsJ56k0fm0Dy6+JoEvsKfhXCWW/9qGCo+4MWbuDPtYBc9HTpQORFRaJ1NrZd3yBOI2EvXQNCP3VhPQ==
    admin-user: AgDLItR/E69RYcINH0+9VIXrLmwGc/ltw8O18yGs2qHW98dwtuahX/EtS4UlvzDMXtaW1/0+B6pld/pEI55swkPplsp5aG074P9bEhB5dRGD2ljTtmvCPJ5xUgVRyJwiiLzqksf08fTo3Dk1h+to2SbJ/sSZ53usWwd8qrwyy4okMipL4EUtHM3MtANT1NXRRWQdULQgGo4Nfr3JFanRO6xBv9nv7k5UP3pKjFg+hmrAtE5jcusxU3+opLtVddcOiYv6SHcnsLenu5yx9yx2kYe+rrKy7dWY4b2XkS0dMwg0rdGbfbxY6xYhMGL7iS9dqhLlMcYex4GdjFLZPSluz6SKENBYmvZPRwhOhEXMnfljKrXb6SIl6wcXduEvfgk5GZ9bXIswoo4q2kCZVglcg4nt3H15Vpbh9iyGrNBBSna8yOL3NBySx7vAdFeU+bEsu0Wpl6wdayrZi1rp0aFs/2bnVWr0gRxukvu3h07EHCEhaiyXNwUn395DmWuLIyXAMYDYT+cOaGvTjmtlDiOVsUmu/ztY0tLxmWlvyaIamW9W4HCFR23pUKtcvgyXTWdMMv9b88zDHfqPiPp4u5Hx6JGEcbhOJIs+WMc0YC/ak+hgqU5yuO3elsTAiXrgUPguJFp96KYpIjmc56BWT3O8WB6+TudcHcQ4tUIR3y1gPx4mTZ21Ops6JQbmmAdL4b4rQ2b/qCj9Yw==
  template:
    metadata:
      name: grafana-admin
      namespace: cloudlite
    type: Opaque
