---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: cloudlite
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBr14qhM6akO2a1kwEmFCrKRvMWoWPoP/rw39e1h/zEH0Klv5fowoQMpCdTaMsL8YKFRJ5K49clIildAo06ushEizfc/AJbTfUurHZeSziPSzkRnPXnco2plTcUqc2sgeL2g500VUUnWjDWL5BmcpcEUL64OJyKFRxwK3wRiNJWmN9ZItNRuKptKNwlm37VkSqQKHYwIe9vzBUv7oetqXyYyce9m3QWS2hbFjC3LHfLw3uuXuj9djm7nLNkEcypTSwF1y+PtVRyaciA4QVktI6QD2qgyJDBNA30avk3KpGxO4IDPu82sT0GeO5+TtMN2oKKgwC3PbOjKKPp/En7RGh4O6p37PvRkSSMpNCL0I83Glp9FUMDhZgxNPhg9YzzNAA2HCrru5ktz2uKkmdQ4Btb7nypQJ7sutaZICbij+IaFhOkkJNry7iYiC7GBhBOfrldTu+3b0xIabKR7gLvxvpv4g344iFIShSW6RFmygskjpfckyWUiS5y5u8+Uo0TSL4CmWUK0/ea9PHzSn3y0PNclIr21srIhbBvkl9/eUdj90dlaKWotZRZeBr1hL6qdHmI/G5eBsdXSSALig6z4iiRGONlhO0hfwTRa5SOU6HtNCP1/6V0oBHETEWqn/J7GVEJgUHza9GPj/Al3T/p/DycSbhAnVyKp55bzYL+DLd4wap25GjOu0L4GPaas9sm1RaTfodq5Xd0oSQKBoELktzaYXq/0B/RUxe79WN8rgDKJg==
    SPRING_DATASOURCE_PASSWORD: AgB3twK3Z+5e3Woq3SEYruG8rLAvsX5M7Mo4n+SkT2xzrhSC2ZCIPZmqAmxA2Le8EIKoA+AQl3pdW+/91+7Vbv1M0fWBehj32tjxPZRL4UHkHFsqVlUJwAFjXrhG+H8FchnqbFD3LBK7MtCjt+Ryin43tI7Ap29kKR+5qyETHtV/u8FxXZsyzREkbTA1na8s1rZ1DAY6Vn53USPnc1lHPMXh/TyQfmYrXUTQ42mos5kzhLHTtajXTwchcO36CD9S0g6PAOGwRbPWVrhmwzYvxXDjp0UKTOM+Sycuz9jC++8e2wy8dHHWgeYRzEKCNDcG7t+08cVtNNouICi2Mk4/vRewj1eHBL36KWrUcTQbZKw/rCXoLzfaA56X6w0/UEJdD4zuf4HFLgzpthO1Kr/IiC8VTvbgqFjnhUseCh8W99yc58yWJJ5c1BLOcrEUgBlx+UyCLMXH/IUYOZM1NGXpS0nfhL0m934+J8rj+Ud5jov5lrnhaF69AvHN0o55jvOGTgLPebRVOK2fbl65A3/7boZFFcCn16TUv7/VanLQKgfwmFRQrgNmKyY1bGmPTW6szFkCefN0OSSRDe9O5DGZ78CIsPIUsOSBv3cns4DemafG+UefchpTRitDI7B6QHmXh26lTS2Th7WXk4YXYcNR5ZPWlRsbhcWgTS9hlc7jS2v2XkSuPLIvOJSdYbZb7b0fqfP8Ug6zx5gpbiTyMXkhb+DjiE/LaiyQmB4JwCrTJKndvA==
  template:
    metadata:
      name: postgres-credentials
      namespace: cloudlite
    type: Opaque
