---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: cloudlite
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBDtttd1cMFCYPxZuzYnZjBRAUamCbqEO23au+M3Swo9/DnFuX0oYJ50jesJ/RondTzmLeS5xCvXpZo/umVXhHPo9LPI9IHbWWG+PkbDHP5mFMNJAL/hJ20ttPCfMY6awT8OmE3VjN86bfzxhs8PPSf5JUnebcZGw0o3JoSUdtCjUx/fUYt+nh94lJsPJ0bMLIaSMZB+3PRJfxnOr3m+ZBzwjyCWcaVLJMoEt+Rv+JwFY+sq8yVIS5Pf68YnqsouTnI+ZwmnxWFeDIiJzeUh3LUFyhM0Bkp2eb+w/1reF5jCbbL/eEJ+gYd1mwoiKBWUIKdIYdqJIB/1YBQGWyzFfnPxcnsd5gABw215E7X26GeCN6vj91nRQ0AY4nnTFmxWGL5nGwb/wC3kF89UAfirwkofWndCZH2GXbZ2zNoN9GCRe1WMr8UCf74Q4RaUT7pe976V/4Kji22wOhaOPwgEBwxt1tBph8w7nnl8lSgRe1W5g7NvXmFXtMyu0DQwielfpRHQ6rAj5xD6MsAGwkZPygEA/NYbiHyyICHTLfkWQylFnZ8cpfXQ9nnrukonxVn1jih/ZLW8H7DEAC9x1ViGOgZaZYiltxDfnVr80NQRFQAtgeHysQ07tpn+y5iVMEE44ChW0JJcbIMDg2V5aPPyvT6Z2pa8CgfY60/FTTiBPpWpJg5kp2lLSiIqexb7uYm11JvR283UXvJA9I0mHviUGXZsoB7Uzi/bRWuENzWCSp9Lw==
    SPRING_DATASOURCE_PASSWORD: AgB5ZJE0hLqHNsXyyLi910NUIwPwEwtIkq8kG96h8IJnY0TBpu0YJfH4LCiVg//UXWelBtAvvEXpoVBcBESwuycCCYmXva4vHXKvilALaYijhWwmHoN1XK3dW3wI1zFyQ7KSELq76lCpIXV912r4D6yWLxgk6wKQ8UlpYfadrLUZ4JqVC0i3NyoTjM0iLIK/WQFL2XBYQjOSSCP0k0Q2RmeiAKrwTNIyK9SiH9i+qsNWs50lxdT9hQdiwz7C/7/5nUEGOuQE08xnIN4ApqmVlZD9C4e1vItdcTwjBAdc7djW3ooijGec5YPAaNvCQIKzjWHsfYC9bkC1L2ZhIruMVramUcOfAESBrvEpg6H0a9D7BT+Wo8I1n/bFKhcSG1cmbI8GW/xvONhWtuAT88ifrFbYxkHp3RcyRk5j7Ll5YmYMEkiEB0kbTcUgN+VyvoOC+P7KnVRjvBrzK5vSS7F2sSHu3JKILx/kd0cdYk+avMmK5ujcQaoJIeR1uqgPfWyUXSk1jAk8QqG5HX2t7D4F3ZgqS5N68kbiMiJrmxlOYDz4DtugV0PtAGqbUDXzmWS7E2iUgHqe5eX3g2DIhQ94lWRzOZQ+uDhr+m2TpL8QbORMv9esQKDMPMS3WXiO7UfxqoN0eG1fx8A49gmVba3x6nZuEg4lJsijbYu4N6sBnuZ8hUlclx/Qj302UTigAZ+DmeQZ8XNPLyId/19hKwNB49Nku0xu0ZuRwhsk7+MixO5xsw==
  template:
    metadata:
      name: postgres-credentials
      namespace: cloudlite
    type: Opaque
