apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudlite
  namespace: {{ .Values.global.namespace }}
spec:
  ingressClassName: traefik
  rules:
    - host: s3.cloudlite.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: s3
                port:
                  number: 8080
    - host: iam.cloudlite.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iam
                port:
                  number: 8081
