---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: iam-jwt-secret
  namespace: cloudlite
spec:
  encryptedData:
    IAM_JWT_SECRET: AgBYcCGCdJQGGwBIPsVgQ5HGhe2aS1Wtqj3Gwtgp6XGYzFZ6tMrUAQeWPl6iDV1mKLelFBxHO99Sac/ImEPFJ9JseSWoPhcGi7+RaI1fcGi+z2Zm6NuJU2iTW6OtZnOyCkaRUd99xvTfflWXKQ5QJ+BQ76oqETnfwo+543KhFncPT887omPlPOGPZwf5hAoaUskSAO3SVBim8L4hOiy3GgjshRord1YzWIEe1O4p0H2KEw3fLh2ICnyauL/4yBjZ0mZtQ/+3YLlkdw9CpNHVc9Zn9XYmFSsUhZGIbyEgmbpJXfbVIUC6aFizcPOfQk0UFGyxH2G9eVRaBoipcE/SgK/Ds6dZj0tKlKzSXGk4+tZMEFj+/jccSeN+Plq7RNc5OIpPr2TL/GQYXek1A6uU9bgaKk9hkVYDfaiicckpnXI0dZktFHEgXCcltlums9tnhThhkabPcFd2Wouhv2BfC8Xwyi5PPcc8WKSs8PfzF3VD3qFAL2P0iRzT1YLpjOEYGPdtf/vtvVwGFDtaUb9uiFPr84IpviBgDdxdpZwQj8J2dvXL0s8FZPRKSAN4yv/ek6gOBZqb4SwfURw8pX1zVcId1FptNFksHAbqDNZAY4VvC+VG8Che9R0sD7cjq9MJ93Y7XFgJjZV97KQzQeR80X2Q9vq2KIiyNTi2/DkN94zuqAxp6KeSdBH79iBpYhELYBgAXRcKkJvGCGAUmOZWMsmeLNGAPJPvzPKAkA+00aAoCZa/UjUFcaa9eGyTtA==
  template:
    metadata:
      name: iam-jwt-secret
      namespace: cloudlite
    type: Opaque
