---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: iam-jwt-secret
  namespace: cloudlite
spec:
  encryptedData:
    IAM_JWT_SECRET: AgCkZ1P1t3zngMuW+HF3fougvghU8rpD5Za4YGUuV7EQOSuarP1Ox4WAKtdTZeO3BFaXfSTow58lxvHAdu2DS3kztSdrDldTj2tByNfkZKjINykeUclYn+29KmpTIoFbKJ/is/PKBla9voaocGmhQxzYR8KALBuDdrqh2EdKUV7ZbhVZ0nJZ2SujEd9PRFqyezi4t+lbrDuZnOXHb9sVYqml/EJB2RV7jjXHq5mYx7M4ZcvE7XdvNSM+9QtCGR6dXMmXH1ctGxH/PxaU+NFWEe1ksZZoN5L/PNyMqViN6k1CfgPXPrdcWFhOrtyq6nJBxCLAI/5s683S8W/SYzPKpp+ybhF1+F4AzIvryWFFSlMlfQA/ipoLgVh6CJ5ngUt1Ow/aZYjBuXVKHVDIwSzhYRSWWYaItWGwgR43IxpLItaTLGZ74VqHLehBN05X0vnkBHbg1Ku+fEylGz0MxLIHlYwG8hYzu/4MNPitMYz3mIaBGxb0XvbfskahoaS+BFmQiWj5NiMGZDabuwH5s6WHr5+1bRG+ok2bGqrhiCpTzqb0KiIbFPk9zqROonpe0k7epUId0zJcgB2c7SlO4SQxUVXYsuKXzuYOc/jwNhJTpCctAqSMA5udfW3nvK6Ef4b2Ti05tNdtuWqLODvFhHg7yeAAD1yzsEQvpYgzQg3FFiTUPhe4Mf0qKl9Bb1Wdxx+Ia1J6U/BquUPgAXSbAwf8TbCKST7apcYrEZXXeUMKuT86BvvrYcJgOUHUehTpkg==
  template:
    metadata:
      name: iam-jwt-secret
      namespace: cloudlite
    type: Opaque
