global:
  namespace: cloudlite

replicaCount: 1

image:
  repository: iam
  tag: "0.1.0"

resources:
  limits:
    cpu: "750m"
    memory: 768Mi
  requests:
    cpu: 375m
    memory: 384Mi

jwt:
  secret: dev-only-insecure-jwt-signing-secret-please-change
  expirySeconds: 900

datasource:
  url: "jdbc:postgresql://postgres:5432/cloudlite"
  username: cloudlite
