server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: s3
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cloudlite}
    username: ${SPRING_DATASOURCE_USERNAME:cloudlite}
    password: ${SPRING_DATASOURCE_PASSWORD:cloudlite}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  mvc:
    throw-exception-if-no-handler-found: true
    formcontent:
      filter:
        enabled: false
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      enabled: false

s3:
  data-dir: ${S3_DATA_DIR:/data}
